services:
  backend:
    build: ./iqa-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./iqa-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped